version: '3.8'
services:
  moobot-obs:
    image: moothecow/moobot-obs:$MOOBOT_VERSION
    container_name: moobot-obs
    restart: unless-stopped
    tty: true
    environment:
      - ASPNETCORE_ENVIRONMENT=$ENVIRONMENT
      - DOTNET_USE_POLLING_FILE_WATCHER=$POLLING_FILE_WATCHER
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=$GLOBALIZATION
      - REGION=$REGION
      - MOOBOT_VERSION=$MOOBOT_VERSION
    volumes:
      - ./appsettings.json:/app/appsettings.$ENVIRONMENT.json
    healthcheck:
      test: curl --fail http://localhost/healthcheck || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 5s
